apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 3s

    scrape_configs:

      # prometheus (own metrics)
      - job_name: prometheus
        static_configs:
          - targets:
              - "localhost:9090"

      # spring (app metrics)
      - job_name: spring
        metrics_path: /api/actuator/prometheus
        static_configs:
          - targets:
              - "spring-metrics.default.svc.cluster.local:8177"
