apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wg-mgr-spring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aleqsonder/wg-mgr.git
    targetRevision: main
    path: spring/k8s/manifests
    directory:
      exclude: argocd.application.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
