apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: ghcr.io/aleqsonder/wg-mgr-spring:20260319-165926
          ports:
            - containerPort: 8177
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: WGMGR_DB_CONN_STR
              valueFrom:
                configMapKeyRef:
                  name: backend
                  key: conn-str
          # TODO: Add readiness/liveness probes
    