apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: 8177
      path: /actuator/prometheus
      interval: 5s
