name: Build and test the application
on:
  pull_request:
    branches:
      - main
    paths:
      # spring
      - spring/src/**
      - spring/pom.xml

      # react
      - react/public/**
      - react/src/**
      - react/index.html
      - react/package*.json
jobs:
  spring:
    uses: ./.github/workflows/spring-check.yml

  react:
    needs:
      - spring
    uses: ./.github/workflows/react-check.yml
