name: Test and build the React service
on:
  # TEST
  push:
    branches:
      - lab4/**

  workflow_call:
defaults:
  run:
    working-directory: react
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install deps
        run: npm install

      - name: Run unit-tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install deps
        run: npm install

      - name: Build the React service
        run: npm run build

  sonar:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          projectBaseDir: react
          args: >
            -Dsonar.projectKey=wg-mgr_react
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_REACT }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
