name: Test and build the Spring service
on:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - spring/src/**
      - spring/pom.xml
defaults:
  run:
    working-directory: spring
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
        
      - name: Run unit-tests
        run: mvn -ff -e -Dtest=VpnUserServiceTest test

  build:
    runs-on: ubuntu-latest
    needs:
      - unit-test
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
        
      - name: Build the Spring service
        run: mvn -B clean package -DskipTests
